rails_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  # 下記の記述はhttp://127.0.0.1:3000/posts/となる
  resources :posts, only: [:index, :new, :create, :edit, :destroy, :update, ]

end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails_app/app/models/post.rb
class Post < ApplicationRecord
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  # 下記はPostというDBからすべて(all)取ってくるという意味
  # @postsはインスタンス生成をしている
  def index
    @posts = Post.all
  end

  # 下記はPostというオブジェクトが作成される(titleとcontentを含んだオブジェクトが作成される)
  # 新しい掲示板のフォーム用のコントローラー設定

  # 定義した名前(ここでいうdef直後の「new」)は/app/views/posts/new.html.erbのnewと名前を一致させる
  def new
    @post = Post.new
  end

  # 下記とすることでtitleとcontentに打ち込まれたものがpost_paramsに格納される
  def create
    @post =Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end
  
  # privateをつけることでその下にdefされたメソッドはこのファイルでしか呼び出せなくなる！（厳格モードみたいな？）
  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/posts_helper.rb
module PostsHelper
end

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_app/app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model: @post,html:{class: "form-container"} do |form| %>
<div class="form-input">
  <%= form.label :title %><%= form.text_field :title %>
</div>
<div class="form-input">
  <%= form.label :content %><%= form.text_area :content %>
</div>
<div class="button-container">
  <%= form.submit "更新",class: "link-button" %>
</div>
<% end %>

rails_app/app/views/posts/index.html.erb
<h1>Hello World</h1>

<div class="button-container"><%= link_to "新しい投稿", new_post_path, class: "link-button" %></div>

<ul>
  <!--

    ===== 条件文記載時のOK例 =====
    <% %>
    ===========================
    ===== 条件文記載時のNG例 =====
    <%= %>
    ===========================
    ・「=」が入ると下記のような値が入ってきちゃう
    [#<Post id: 1, title: "test", content: "test", created_at: "2023-09-07 13:25:58.440769000 +0000", updated_at: "2023-09-07 13:25:58.440769000 +0000">, #<Post id: 2, title: "test2", content: "test2", created_at: "2023-09-07 13:33:35.555897000 +0000", updated_at: "2023-09-07 13:33:35.555897000 +0000">]
   -->
  <% @posts.each do |post|  %>
  <li>
    <h2><%= post.title %></h2>
    <p><%= post.content %></p>
    <span><%= post.created_at %></span>
  </li>
  <% end %>
</ul>

rails_app/app/views/posts/new.html.erb
<h1>新しい投稿</h1>

<%= form_with model: @post,html:{class: "form-container"} do |form| %>
<div class="form-input">
  <%= form.label :title %><%= form.text_field :title %>
</div>
<div class="form-input">
  <%= form.label :content %><%= form.text_area :content %>
</div>
<div class="button-container">
  <%= form.submit "投稿",class: "link-button" %>
</div>
<% end %>